### ISSUE TITLE
Add option for `gnatss` for user flag file to remove bad data

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/offshore-geodesy#141]
## Overview

There need to be a way that a user can add their own manual data flagging for data that will need to be excluded in the solve computation. This can be a config path to a csv file.

**Comment by lsetiawan** [comment]
This may be allowing the `InputData` to also take in a list for `path` attribute as well as such that a user can put a path to additional deletion files that may not be same format.

https://github.com/uw-ssec/offshore-geodesy/blob/27375d404f6dd6ac7a445f4ae1a4ea8bffa2de9f/src/gnatss/configs/io.py#L9-L29

In example, currently the old program uses `deletns.dat` file for the deletions file, but now we use csv file. An idea for this would allow the follow configuration to work:

```yaml
input_files:
    sound_speed:
      path: ../2022/NCL1/ctd/CTD_NCL1_Ch_Mi
    travel_times:
      path: ../2022/NCL1/**/WG_*/pxp_tt
    gps_solution:
      path: ../2022/NCL1/**/posfilter/POS_FREED_TRANS_TWTT
    deletions:
      path:
        - ../2022/NCL1/GPS_A_center/deletns.dat
        - ../qa.csv
```

Notice that `deletions.path` is now a list and now `qa.csv` is included. `qa.csv` must have a consistent format such that it contains start and end time.. this can be as iso string or j2000.

Column standard:

- `starttime: str | int`: Start time string or j2000 count
- `endtime: str | int`: End time string or j2000 count
- `notes: str`: A note about this flag
