### ISSUE TITLE
File inputs not able to be a single file

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/offshore-geodesy#184]
## Overview

John has discovered in #175 that when input files is set to be a single file rather than a glob path, it doesn't work. For example, if a user set a single file for pxp_tt like:

```yaml
input_files:
    travel_times: 
      path: ./my_dir/pxp_tt
```

this will fail!

**Comment by lsetiawan** [comment]
The key function that creates the listing of path strings when glob path is given `**` is called `gather_files`:

https://github.com/uw-ssec/offshore-geodesy/blob/d0f2bd01e387c287aa2b78eaaab007a82337a013/src/gnatss/main.py#L56-L59

The `gather_files`

**Comment by lsetiawan** [comment]
## Proposed Solution

A solution to the above for this issue should be that every loader inputs should be a `List[str]` and that `gather_files` dictionary should output a `List[str]` to the file path.

**Sample config input**

```yaml
input_files:
    sound_speed:
      path: ./tests/data/2022/NCL1/ctd/CTD_NCL1_Ch_Mi
    travel_times:
      path: ./tests/data/2022/NCL1/208/WG_20220727/pxp_tt
    gps_solution:
      path: ./tests/data/2022/NCL1/208/posfilter/POS_FREED_TRANS_TWTT
    deletions:
      path: ./tests/data/2022/NCL1/deletns.dat
```

**The above inputs should output the following for the `gather_files` function**

```python
{
  "sound_speed": ["absolute/path/to/tests/data/2022/NCL1/ctd/CTD_NCL1_Ch_Mi"],
  "travel_times": ["absolute/path/to/tests/data/2022/NCL1/208/WG_20220727/pxp_tt"],
  "gps_solution": ["absolute/path/to/tests/data/2022/NCL1/208/posfilter/POS_FREED_TRANS_TWTT"],
  "deletions": ["absolute/path/to/tests/data/2022/NCL1/deletns.dat"],
}
```

**The following functions should not fail when their respective list of path is given**

`load_sound_speed`

https://github.com/uw-ssec/offshore-geodesy/blob/d0f2bd01e387c287aa2b78eaaab007a82337a013/src/gnatss/loaders.py#L35

`load_deletions`

https://github.com/uw-ssec/offshore-geodesy/blob/d0f2bd01e387c287aa2b78eaaab007a82337a013/src/gnatss/loaders.py#L262-L264
